"""add_transfers_table_and_opening_balances

Revision ID: 9d6968563db4
Revises: n0i1j2k3l4m5
Create Date: 2026-04-18 10:44:56.363132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6968563db4'
down_revision: Union[str, Sequence[str], None] = 'n0i1j2k3l4m5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('account_balances',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('account_name', sa.String(), nullable=False),
        sa.Column('opening_balance', sa.Float(), nullable=True),
        sa.Column('as_of_date', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_account_balances_id'), 'account_balances', ['id'], unique=False)
    except Exception as e:
        print(f"Skipping account_balances creation: {e}")

    try:
        op.create_table('transfers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('from_account', sa.String(), nullable=False),
        sa.Column('to_account', sa.String(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_transfers_id'), 'transfers', ['id'], unique=False)
    except Exception as e:
        print(f"Skipping transfers creation: {e}")
    try:
        op.add_column('debts', sa.Column('opening_balance', sa.Float(), nullable=True))
    except Exception as e:
        print(f"Skipping adding opening_balance column: {e}")
    try:
        op.alter_column('expenses', 'is_transfer',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text("'0'"))
        op.create_unique_constraint('uq_income_entry', 'income', ['user_id', 'date', 'amount', 'description'])
        op.alter_column('subscriptions', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        op.alter_column('subscriptions', 'user_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        op.alter_column('subscriptions', 'name',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=False)
        op.alter_column('subscriptions', 'category',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('subscriptions', 'status',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True,
                   existing_server_default=sa.text("'active'"))
        op.alter_column('subscriptions', 'currency',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True,
                   existing_server_default=sa.text("'LKR'"))
    except Exception as e:
        print(f"Skipping alter column operations locally for sqlite: {e}")
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    
    # --- DATA MIGRATION ---
    bind = op.get_bind()
    
    # 1. Migrate is_transfer expenses into transfers table
    # Using SQLAlchemy core mapping to avoid SQL dialect issues
    try:
        bind.execute(sa.text("""
            INSERT INTO transfers (user_id, date, from_account, to_account, amount, description, created_at)
            SELECT user_id, date, COALESCE(account, 'Unknown'), 'Transfer', amount, description, CURRENT_TIMESTAMP
            FROM expenses 
            WHERE is_transfer = true OR is_transfer = 1
        """))
        bind.execute(sa.text("DELETE FROM expenses WHERE is_transfer = true OR is_transfer = 1"))
    except Exception as e:
        print(f"Skipping transfer migration: {e}")

    # 2. Inject opening balances into debts table safely
    updates = [
        ("BOC Credit Card", 309523),
        ("Sampath Credit Card", 88790),
        ("NDB Card", 97685),
        ("NTB AMEX", 120000),
        ("NTB AMEX Credit Card", 120000)
    ]
    for name, ob in updates:
        try:
            bind.execute(sa.text(f"UPDATE debts SET opening_balance = {ob} WHERE name = '{name}'"))
        except Exception:
            pass
            
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'LKR'"))
    op.alter_column('subscriptions', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.alter_column('subscriptions', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_income_entry', 'income', type_='unique')
    op.alter_column('expenses', 'is_transfer',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('debts', 'opening_balance')
    op.drop_index(op.f('ix_transfers_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_account_balances_id'), table_name='account_balances')
    op.drop_table('account_balances')
    # ### end Alembic commands ###
